name = "po3m"
pages_build_output_dir = "./public"
compatibility_date = "2026-04-20"

[[d1_databases]]
binding = "DB"
database_name = "po3m-db"
database_id = "33c82c79-28b6-4415-b7a5-b95b2cd4541b"

[vars]
ENVIRONMENT = "production"
