name = "po3m"
main = "functions/api/submit.js"
compatibility_date = "2026-04-20"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "po3m-db"
database_id = "33c82c79-28b6-4415-b7a5-b95b2cd4541b"

[vars]
ENVIRONMENT = "production"
